Repository Teahouse-Studios/mcwzh-meme-resourcepack, pull requests merged in 2020-02, with the labels that each got.

#18 鲨后缀.mcpack
  README.md
Labels: 已解决, 漏洞

#21 Just make a change
  assets/minecraft/lang/zh_meme.json
Labels: 已合并, 已解决

#16 made some changes - minecraft:phantom
  assets/minecraft/lang/zh_meme.json
Labels: 已合并, 已解决

#24 Copy from warframe's meme
  assets/minecraft/lang/zh_meme.json
Labels: 推迟, 等待查核, 问题

#25 Music disc
  assets/minecraft/lang/zh_meme.json
Labels: 改进, 等待查核, 请求帮助

#29 A suggestion
  assets/minecraft/lang/zh_meme.json
Labels: 稍后关闭/解决, 通过

#31 ->biome.minecraft.nether_wastes
  assets/minecraft/lang/zh_meme.json
Labels: 已合并, 已解决

#32 Update README.md
  README.md
Labels: 已合并, 已解决

#33 Update zh_meme.json
  assets/minecraft/lang/zh_meme.json
Labels: 稍后关闭/解决, 通过

#30 Update zh_meme.json
  assets/minecraft/lang/zh_meme.json
Labels: 改进, 等待回复, 等待查核, 通过

#35 Update pack.mcmeta
  pack.mcmeta
Labels: 改进, 沟通, 请求帮助, 通过
