Repository Teahouse-Studios/mcwzh-meme-resourcepack, pull requests merged in 2020-12, with the labels that each got.

#139 增加OpenComputers模组文本
  mods/opencomputers.json
Labels: 改进, 等待查核

#140 修改opencomputers.json
  mods/opencomputers.json
Labels: 改进, 等待回复, 等待查核

#143 添加computronicsMod
  mods/Computronics.json
Labels: 改进, 等待回复

#144 多洛洛狼材质
  modules/doro_wolf_texture/assets/minecraft/textures/entity/wolf/wolf.png
  modules/doro_wolf_texture/assets/minecraft/textures/entity/wolf/wolf_angry.png
  modules/doro_wolf_texture/assets/minecraft/textures/entity/wolf/wolf_tame.png
  modules/doro_wolf_texture/module_manifest.json
Labels: 沟通, 等待查核
