Repository Teahouse-Studios/mcwzh-meme-resourcepack, pull requests merged in 2020-07, with the labels that each got.

#75 水
  assets/minecraft/lang/zh_meme.json
Labels: 改进, 等待查核

#77 桃木剑
  assets/minecraft/lang/zh_meme.json
Labels: 改进, 稍后关闭/解决, 等待查核

#78 ZH9的奇奇怪怪的东西
  optional/BUGJUMP/assets/minecraft/textures/gui/title/mojang.png
  optional/Lie-nus_and_more_things/assets/minecraft/textures/painting/back.png
  optional/Lie-nus_and_more_things/assets/minecraft/textures/painting/burning_skull.png
  optional/Lie-nus_and_more_things/assets/minecraft/textures/painting/bust.png
  optional/Lie-nus_and_more_things/assets/minecraft/textures/painting/donkey_kong.png
  optional/Lie-nus_and_more_things/assets/minecraft/textures/painting/fighters.png
  optional/Lie-nus_and_more_things/assets/minecraft/textures/painting/graham.png
  optional/Lie-nus_and_more_things/assets/minecraft/textures/painting/match.png
  optional/Lie-nus_and_more_things/assets/minecraft/textures/painting/pigscene.png
  optional/Lie-nus_and_more_things/assets/minecraft/textures/painting/pointer.png
  optional/Lie-nus_and_more_things/assets/minecraft/textures/painting/skull_and_roses.png
  optional/meme_splashes/assets/minecraft/texts/splashes.txt
Labels: 稍后关闭/解决, 等待回复

#82 提请合并 · 2020.07.12 · WTP016-CN
  assets/minecraft/lang/zh_meme.json
Labels: WIP, 改进, 稍后关闭/解决, 请求帮助

#83 Per #80
  assets/minecraft/lang/zh_meme.json
Labels: WIP, 改进

#87 “这是一个小修改”
  optional/meme_splashes/assets/minecraft/texts/splashes.txt
Labels: WIP, 改进

#88 同步一下
  optional/meme_splashes/assets/minecraft/texts/splashes.txt
Labels: WIP

#100 加入了爬行动作等
  assets/minecraft/lang/zh_meme.json
Labels: 改进, 稍后关闭/解决, 通过

#102 创建新的世界 -> 开天辟地
  assets/minecraft/lang/zh_meme.json
Labels: 改进, 稍后关闭/解决, 通过

#108 Update end.txt
  modules/a_letter/assets/minecraft/texts/end.txt
Labels: 改进, 稍后关闭/解决, 通过
