Repository Teahouse-Studios/mcwzh-meme-resourcepack, pull requests merged in 2021-03, with the labels that each got.

#157 ✨ 鸡，蓝色
  meme_resourcepack/assets/minecraft/lang/zh_meme.json
  modules/LocusAzzurro/add.json
  modules/LocusAzzurro/assets/minecraft/textures/entity/chicken.png
  modules/LocusAzzurro/assets/minecraft/textures/item/feather.png
  modules/LocusAzzurro/module_manifest.json
  modules/choice_modules_1/module_manifest.json
Labels: 改进, 沟通, 通过

#158 鸡蛋，蓝色
  modules/LocusAzzurro/assets/minecraft/models/item/chicken_spawn_egg.json
  modules/LocusAzzurro/assets/minecraft/textures/item/egg.png
  modules/LocusAzzurro/assets/minecraft/textures/item/locus_azzurro_spawn_egg.png
Labels: 已合并, 已解决, 改进

#156 添加并更改一些细节
  meme_resourcepack/assets/minecraft/lang/zh_meme.json
  mods/optifine.lang
  modules/BlueTubePoster/assets/minecraft/blockstates/dead_tube_coral_wall_fan.json
  modules/BlueTubePoster/assets/minecraft/models/block/poster/poster_0.json
  modules/BlueTubePoster/assets/minecraft/models/block/poster/poster_1.json
  modules/BlueTubePoster/assets/minecraft/models/block/poster/poster_2.json
  modules/BlueTubePoster/assets/minecraft/models/block/poster/poster_3.json
  modules/BlueTubePoster/assets/minecraft/models/block/poster/poster_4.json
  modules/BlueTubePoster/assets/minecraft/models/block/poster/poster_5.json
  modules/BlueTubePoster/assets/minecraft/models/block/poster/poster_6.json
  modules/BlueTubePoster/assets/minecraft/models/block/poster/poster_father.json
  modules/BlueTubePoster/assets/minecraft/textures/block/dead_tube_coral_fan.png
  modules/BlueTubePoster/assets/minecraft/textures/block/dead_tube_coral_fan.psd
  modules/BlueTubePoster/assets/minecraft/textures/block/poster/ancient_debris.png
  modules/BlueTubePoster/assets/minecraft/textures/block/poster/ancient_debris.psd
  modules/BlueTubePoster/assets/minecraft/textures/block/poster/bedrock_earth.png
  modules/BlueTubePoster/assets/minecraft/textures/block/poster/bedrock_earth.psd
  modules/BlueTubePoster/assets/minecraft/textures/block/poster/creeper_aw_man.png
  modules/BlueTubePoster/assets/minecraft/textures/block/poster/cyber_craft.png
  modules/BlueTubePoster/assets/minecraft/textures/block/poster/cyber_craft.psd
  modules/BlueTubePoster/assets/minecraft/textures/block/poster/indihome_paket_phoenix.png
  modules/BlueTubePoster/assets/minecraft/textures/block/poster/indihome_paket_phoenix.psd
  modules/BlueTubePoster/assets/minecraft/textures/block/poster/microjang.png
  modules/BlueTubePoster/assets/minecraft/textures/block/poster/microjang.psd
  modules/BlueTubePoster/assets/minecraft/textures/block/poster/under_mineshaft.png
  modules/BlueTubePoster/assets/minecraft/textures/block/poster/under_mineshaft.psd
  modules/BlueTubePoster/module_manifest.json
  modules/rainbow_enchanting/assets/minecraft/textures/misc/enchanted_item_glint.png
  modules/rainbow_enchanting/module_manifest.json
Labels: 改进
